from typing import List, Tuple
import datetime

def format_time(ms: int) -> str:
    """Converts milliseconds to MM:SS format."""
    seconds = int(ms / 1000)
    minutes = seconds // 60
    seconds = seconds % 60
    return f"{minutes:02}:{seconds:02}"

def generate_description(timestamps: List[Tuple[str, int]]) -> str:
    """
    Generates a YouTube-style description from timestamps.
    
    Args:
        timestamps (List[Tuple[str, int]]): List of (filename, start_time_ms).
        
    Returns:
        str: The formatted description string.
    """
    lines = ["🎵 Mixtape Tracklist 🎵\n"]
    
    for filename, start_ms in timestamps:
        # Remove extension for cleaner look
        clean_name = filename.rsplit('.', 1)[0]
        time_str = format_time(start_ms)
        lines.append(f"{time_str} - {clean_name}")
        
    lines.append("\n✨ Generated by Automated YouTube Mixtape Creator ✨")
    return "\n".join(lines)

def save_description(content: str, output_path: str):
    """Saves the description to a text file."""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
